# Generated by Django 3.0.7 on 2020-06-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcontent', '0002_auto_20200613_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='user.svg', upload_to='images/'),
        ),
    ]
