# Generated by Django 3.0.7 on 2020-06-23 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcontent', '0004_auto_20200623_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='image',
            field=models.FileField(default="'setting.MEDIA_ROOT/user.svg", upload_to='images/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'svg'])]),
        ),
    ]
