# Generated by Django 3.0.7 on 2020-06-24 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogcontent', '0006_auto_20200623_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.FileField(default='', upload_to='post/images/', validators=[django.core.validators.FileExtensionValidator(['svg'])]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='abstract',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(),
        ),
    ]
